name: Deploy Inference Endpoint and API

on:
  push:
    branches:
      - main
    paths:
      - src/model_deploy/**
      - cfg/model_deploy.yaml

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{secrets.IAM_ROLE}}
          aws-region: ${{secrets.AWS_REGION}}
          # role-skip-session-tagging: true
          # role-duration-seconds: 1200

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Upload MLflow model to S3
        run: |
          python3 scripts/manage_mlflow_model.py --prepare-model
          echo MLFLOW MODEL UPDLOADED TO S3

      - name: Transition Model to Staging
        run: |
          python3 scripts/manage_mlflow_model.py --transition-staging
          echo TRANSITION MLFLOW MODEL TO STAGING

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    env:
      DEPLOYMENT_ENV: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy CDK stack to Staging
        uses: sofianhamiti/composite-action-cdk-deploy@main
        with:
          cdk_version: 2.41.0
          folder: src/model_deploy/stack
          aws_account: ${{secrets.ACCOUNT_ID}}
          aws_region: ${{secrets.AWS_REGION}}
          iam_role: ${{secrets.IAM_ROLE}}

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

  test-api:
    runs-on: ubuntu-latest
    needs:
      - build
      - deploy-staging
    env:
      DEPLOYMENT_ENV: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{secrets.IAM_ROLE}}
          aws-region: ${{secrets.AWS_REGION}}
          # role-skip-session-tagging: true
          # role-duration-seconds: 1200

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Test Staging API
        run: |
          python3 test/test_endpoint.py
          echo API TEST SUCCESSFUL

      - name: Transition Model to Prod
        run: |
          python3 scripts/manage_mlflow_model.py --transition-prod
          echo TRANSITION MLFLOW MODEL TO PRODUCTION

  deploy-prod:
    runs-on: ubuntu-latest
    needs:
      - build
      - deploy-staging
      - test-api
    env:
      DEPLOYMENT_ENV: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy CDK stack to Production
        uses: sofianhamiti/composite-action-cdk-deploy@main
        with:
          cdk_version: 2.41.0
          folder: src/model_deploy/stack
          aws_account: ${{secrets.ACCOUNT_ID}}
          aws_region: ${{secrets.AWS_REGION}}
          iam_role: ${{secrets.IAM_ROLE}}
